### ISSUE TITLE
Torches and lanterns burn fuel twice as fast when in inventory

### ISSUE THREAD

**Issue by TheInfine** [WolfieWaffle/Hardcore-Torches-Forge#14]
Requires config option `tickInInventory` to be enabled.

**Comment by WolfieWaffle** [comment]
So when they are in the inventory they burn twice as fast as when on the ground? Is this a recent issue because it may be caused by my Curios integration.

**Comment by TheInfine** [comment]
No, I just tested and it happens on 1.2.3 as well.

**Comment by WolfieWaffle** [comment]
weird, I will look into it
