### ISSUE TITLE
Suggestion: Disable sound of extinguishing when fuel runs out

### ISSUE THREAD

**Issue by TheInfine** [WolfieWaffle/Hardcore-Torches-Forge#15]
It doesn't make sense that torches and lanterns make a sound when their fuel runs out. They should make the sound only when being extinguished while burning. A config option for this would be nice. Also the extinguishing sound is way too loud compared to a campfire for example.

**Comment by TheInfine** [comment]
+ Currently it doesn't play the sound when the fuel runs out and the torch is in hand.

**Comment by WolfieWaffle** [comment]
alright I can add that
