### ISSUE TITLE
Unlit torches don't stack correctly

### ISSUE THREAD

**Issue by TheInfine** [WolfieWaffle/Hardcore-Torches-Forge#17]
This happens because unlit torches get a Fuel NBT tag when they're placed on the ground.

Steps to reproduce:
1. Craft/give yourself unlit torches
2. Place a few of them on the ground
3. Break them
4. They will go into a different slot

**Comment by WolfieWaffle** [comment]
You are finding like a million bugs lol, got this one fixed as well. I appreciate the bugtesting.
