### ISSUE TITLE
[suggestion] make player's arm extend when holding a lit torch or lantern

### ISSUE THREAD

**Issue by ekiplier** [WolfieWaffle/Hardcore-Torches-Forge#18]
I think it would be a cool addition, because it's strange that it happens with minecraft torches and lanterns but not with the items from this mod

**Comment by WolfieWaffle** [comment]
hm, like in third person view? I didn't know it did that

**Comment by ekiplier** [comment]
Yeah, I was playing with first person model mod so it's more noticeable to me.

**Comment by WolfieWaffle** [comment]
This is from Not Enough Animations and can be configured
