### ISSUE TITLE
Suggestion: Replace naturally generated unlit lanterns with lit lanterns (as a config option)

### ISSUE THREAD

**Issue by juicebin** [WolfieWaffle/Hardcore-Torches-Forge#24]
Using 'ChoiceTheorem's Overhauled Village' mod, the villages spawn with lanterns. These lanterns are replaced with unlit lanterns, I assume done purposefully. Perhaps it could be a config option to allow these to be replaced with lit lanterns? Not necessarily everlasting lantern, but a fully lit lantern! Perhaps even villagers can refuel these lanterns if given the resources?

**Comment by WolfieWaffle** [comment]
hm, sounds like a bug. they should be lit.

**Comment by juicebin** [comment]
Was this fixed only in the `.jar` that was sent to me in your Discord server, or was it fixed in the releases for 1.18.2 and 1.19?
Just wanna know if I should close this 😄

**Comment by WolfieWaffle** [comment]
it should be fixed on the most recent ones, ill check the changelog I put on curseforge

**Comment by WolfieWaffle** [comment]
well, I THINK I fixed it for fabric, but I definitely did for forge on the most recent uploads
