### ISSUE TITLE
Incompatible with Dynamic Lights mod

### ISSUE THREAD

**Issue by zargogo** [WolfieWaffle/Hardcore-Torches-Forge#29]
https://www.curseforge.com/minecraft/mc-mods/dynamic-lights

no matter the config settings, torches held in the hand don't light up correctly. dropped lit torches also don't light correctly

**Comment by WolfieWaffle** [comment]
I know this isn't a full fix but you can always use Lucent, it does basically the same thing and I have hardcoded support for it already in this mod

**Comment by zargogo** [comment]
Unfortunately, Lucent is not compatible with the sodium forge port that I'm using so I can't :-( but no worries, I found a mod called Magnesium/Rubidium Dynamic Lights and that works for me
