### ISSUE TITLE
Crash on Torch Placement

### ISSUE THREAD

**Issue by PotionSeeker** [WolfieWaffle/Hardcore-Torches-Forge#3]
**General Info**
Hardcore Torches crashes moments after a torch is placed down. This has been tested without any other mods installed and on the most up-to-date version of forge.

**Client Info**
- Minecraft Version - 1.18.1
- Forge Version - Forge - 1.18.1 - 39.0.59 - universal
- Installed Mods - Hardcore Torches

**Crash Report**
Version 1.0.0 - [crash-2022-01-25_12.03.13-server.txt](https://github.com/WolfieWaffle/Hardcore-Torches-Forge/files/7933400/crash-2022-01-25_12.03.13-server.txt)
Version 1.1.3 - [crash-2022-01-25_12.12.32-server.txt](https://github.com/WolfieWaffle/Hardcore-Torches-Forge/files/7933450/crash-2022-01-25_12.12.32-server.txt)

**Comment by WolfieWaffle** [comment]
Weird, I don't know how that particular crash happens I've been running it consistently. I think I see the problem though, just not sure how I ever was able to run it myself given this error.

I'm fixing it now, but could you also post your config file for this mod? I'm wondering if it only happened under a specific configuration.

**Comment by WolfieWaffle** [comment]
Nevermind I don't think it's config related. I believe the newest version of forge deletes a method I was calling. If you use a lower version of forge it will probably fix it, but I will update my own forge so that it compiles properly.

**Comment by PotionSeeker** [comment]
Yep, I just tested a few different versions of forge and noticed some pretty interesting things. Forge Version 39.0.44 works perfectly - the torches can be placed without any problems. Forge Version 39.0.53 seems to cause the game to just crash on startup, and yet Forge Version 39.0.56 allows the game to startup but crashes when a torch is placed in world. Also, In case it might help, I was just using the default configs when testing the mod.

**Comment by WolfieWaffle** [comment]
The issue as far as I can tell was that a certain method was being called in my mod which did not exist in the latest version. My workspace was using an old version, so it worked fine, but not when it was updated. I have changed to the latest version of forge, which gave me a compiler error as expected, which I fixed. I have uploaded a new file, tell me if it does not work.

**Comment by PotionSeeker** [comment]
Nice work! The torches can be placed without causing any crashing. 
The only thing I would report is that whenever a torch or lantern is placed, it causes a 'fatal' message to be printed to the log. I've seen another mod have this issue as it seems that they also attempt to call the "net.minecraft.nbt.CompoundTag.m_128441_(String)" method. I don't personally mind as the game runs fine otherwise, but it may be something you might want to look into. I've attached a sample of the issue just in case it'll help in any way:
[Log_Message.txt](https://github.com/WolfieWaffle/Hardcore-Torches-Forge/files/7937692/Log_Message.txt)
