### ISSUE TITLE
Is Lucent support changed?

### ISSUE THREAD

**Issue by susan3333333** [WolfieWaffle/Hardcore-Torches-Forge#32]
On 1.16.5 everything just worked, but now I have moved to 1.19.2 and it doesn't fully work.
The handheld dynamic lighting seems fine, but the hardcore torches/lucent/curios support isn't working?
The lantern in the curios slot does not provide light.

**Comment by WolfieWaffle** [comment]
what mods are you using, and what version of hardcore torches?

**Comment by susan3333333** [comment]
Minecraft 1.19.2
Forge 43.2.0

Hardcore Torches 1.19.2-2.6

Mods:

Additional Lights
Additional Structures
Adorn
Advanced Chimneys
Advanced Finders
Alex's Delight
Alex's Mobs
Aquaculture 2
Aquatic Additions
Architectury
Artifacts
AutoFish
AutoRegLib
Balanced Crates
Balloon Box
Balm
Beekeeper
Better Animals Plus
Blueprint
Bookshelf
Builders Crafts & Additions
Camera Mod
Campanion
Campsite Structures
Catalogue
Cave Enhancements
Chalk
Chimes 
ChoiceTheorem's Overhauled Village - Farmer's Delight Compat
ChoiceTheorem's Overhauled Village - Waystone Compat
ChoiceTheorem's Overhauled Villages
Citadel
Cloth Config Forge
Clumps
Collective
Comforts
Compressed
Compressed items
Configured
Convenient Curios Container
Cooking for Blockheads
Corail Pillar
Corail Recycler
Cottonly
Cozy
Curios API
Cursed Crypts
Cyclic
Delightful
Despawning Eggs Hatch
Domum Ornamentum
Dramatic Doors
Drink Beer Refill
Dungeons Enhanced
Enchantment Descriptions
Exlines Awnings
Expandability
Fantasy's Furniture
Farmer's Compats
Farmer's Delight
Festive Delight
Fixed Anvil Repair Cost
Copper Tools
Forge Endertech
Furnish
GeckoLib
Glow Sticks
Gobber 2
Gobber Delight
The Graveyard
Growthcraft Trapper
Guard Villagers
Handcrafted
Hangman
Hardcore Torches
Highlighter
Hourglass
Iceberg
Illuminations
Immersive Paintings
Infinite Trading
Inventory Totem
Item Zoom
Jade
Jolly Boxes
Jumbo Furnace
Just Enough Effect Descriptions
Just Enough Items
Just Enough Resources
Kiwi
Kotlinforforge
Labels
Large Ore Deposits
Lighting Wand
Lightman's Currency
Lightstones
Little Geode
Loot Bundles
Lucent
Luggage
Lumberjack
Macaw's Bridges
Macaw's Fences and Walls
Macaw's Furniture
Macaw's Paintings
Macaw's Paths and Pavings
Macaw's Roofs
Macaw's Windows
Majrusz Library
Majrusz's Accessories
Majrusz's Enchantments
Majrusz's Progressive Difficulty
Material Elements
Matmos
MCPitanLibarch
Moonlight Library
MrCrayfish's Furniture Mod
Nameless Trinkets
Night Lights
No Hostiles around Campfire
No Telemetry
Notes
Openstairs
Optifine
Paladin's Furniture
Passable Foliage
Patchouli
Path under Gates
Philip's Ruins
Placeable Blaze Rods
Platforms
Polymorph
Project MMO 
Quark
Quick Paths
Recast
Regrowth
Relics
Reliquary
Repurposed Structures
Resourceful Tools
Serene Seasons
Sereneseasonfix
ShetiPhian-Core 
Shroom Dealers
Signpost
Sky Villages
Small Stairs
Snow Pig 
Snowy Spirit
SpawnBalanceUtility
Spider Produce Webs
Structure Gel API
Subterrestial
Supplementaries
Terraqueous
This Rocks
Tool Belt
Tough as Nails
Towns and Towers
Trapper Pelts
Tumbleweed
U Team Core
Underground Villages
Useful Backpacks
Vanilla+tools
Waddles
Water Strainer
Water Condenser
Waystone Towers
Waystone Waypoint Maker
Waystones
William Wythers Overhauled Overworld
Xaero's Minimap
Xaero's World Map 
Yung's API
Yung's Better Desert Temples
Yung's Better Dungeons
Yung's Better Mineshafts
Yung's Better Ocean Monuments
Yung's Better Strongholds
Yung's Better Witch Huts
Yung's Bridges
Yung's Extras

**Comment by WolfieWaffle** [comment]
hm im trying to download all these mods, but really quick could you try it without optifine? optifine is known to mess with a lot of client side stuff

**Comment by susan3333333** [comment]
I could've sworn I already tried without Optifine? But that seems to be it.Sorry.......

    On Tuesday, January 17, 2023 at 05:11:20 p.m. EST, WolfieWaffle ***@***.***> wrote:  
 
 


hm im trying to download all these mods, but really quick could you try it without optifine? optifine is known to mess with a lot of client side stuff

**Comment by WolfieWaffle** [comment]
No problem. I wish there was an easy fix, but unfortunately Optifine is known to kind of rewrite all the rendering code and it's not really feasible to make things work with it. However there are other performance mods that might word better, you could try Rubidium for example.

You can also try helping things with the explanation here, it helped me a lot.

https://www.reddit.com/r/feedthebeast/comments/5jhuk9/modded_mc_and_memory_usage_a_history_with_a/
