### ISSUE TITLE
[Suggestion] Torches/lanterns in world gen don't burn out naturally

### ISSUE THREAD

**Issue by polykatt** [WolfieWaffle/Hardcore-Torches-Forge#38]
Torches and lanterns that generate in the world such as those in villages behave just like vanilla torches until picked up by a player. So they won't burn out on their own while also maintaining that players can't bypass the mod by simply picking up a forever torch from one of these structures. This would be great especially in villages preventing mob spawns so that all of them don't die when the lights burn out.

Not sure if this is already how it works, I just installed this mod and had this idea. I also had a question; does the mod replace torches and lanterns that generate as chest loot?

**Comment by WolfieWaffle** [comment]
It doesn't replace chest loot right now, but in the latest version it should now replace generated structures. I will make a new issue for loot tables.
