### ISSUE TITLE
[Request] Ability to fuel and light torches and/or lanterns in inventory or without placing items down

### ISSUE THREAD

**Issue by katubug** [WolfieWaffle/Hardcore-Torches-Forge#39]
Hi! I'm a modpack maker, and I'm considering making the switch from Realistic Torches to this one, because I love the feature you add that allows torches/lanterns to burn out while being held or rained on.

However, one thing I prefer about RT is that they add a "Matchbox" item which allows the player to place unlit torches in a crafting grid with it, to produce the lit variants. I would really love a feature like this in your mod. I was attempting to add support myself, through kubejs, but I'm not sure that it's possible for me to do so. So I figured I'd come here and ask.

In an ideal world, this is what I'd love:
- Being able to light a torch without placing it down or crafting a new one.
- Being able to fill and light a lantern without placing it down.
- Lanterns/torches flickering as they reach low fuel.

The first two items would be, I think, most easily done via shapeless crafting recipes. However, it'd be super cool instead to have a mechanic similar to Create's Rose Quartz polishing, where you'd hold (in this case), the torch/lantern in one hand, and the matchbox/flint in the offhand, and then right click.

Anyway, I realize this is a somewhat big ask, and I'd be happy to donate a couple of bucks to the cause, if you feel up to it! Thanks for your time!

**Comment by WolfieWaffle** [comment]
That should be possible, what do you mean by flickering exactly? The light level of the block changing?

**Comment by katubug** [comment]
Yes! Exactly. Also I have to admit that I forgot I was using a dynamic
lighting mod to control the handheld light, and that's not handled by your
mod at all lol. That was mostly what I wanted the flickering for. 😅

**Comment by WolfieWaffle** [comment]
This should be added, do you need it updated to 1.20.4 or above?

**Comment by katubug** [comment]
Awesome! I'm on 1.20.1 so I don't need it any higher than that. Thank you
so very much!
