### ISSUE TITLE
Compatibility with Amendments' Custom Lamp Holding (and maybe wall placement?)

### ISSUE THREAD

**Issue by katubug** [WolfieWaffle/Hardcore-Torches-Forge#40]
Hi! Thanks again for the other changes you made :D

I do have another request, if that's okay. <3 The mod Amendments changes the way players hold up lanterns in a way which is really immersive and I love it, I was wondering if it would be possible to add compatibility for the way your lanterns are held?

I also asked over there: https://github.com/MehVahdJukaar/amendments/issues/128

But I figured I'd ask in both places. Thanks so much for your time!

**Comment by WolfieWaffle** [comment]
This should be added in the latest version!
