### ISSUE TITLE
Torches can be lit by right clicking an unlit campfire

### ISSUE THREAD

**Issue by TheInfine** [WolfieWaffle/Hardcore-Torches-Forge#7]
This happens because campfires store their lit state in blockstates.

If this is fixed it would also be cool if lit furnaces, smokers, blast furnaces and maybe candles and candle cakes could be used for lighting torches.

**Comment by WolfieWaffle** [comment]
Hm I didn't think of that. The problem is that everyone says I should be using block tag json files, but those don't allow for blockstates. I hear there may be another proper solution, but it might take a bit.

**Comment by TheInfine** [comment]
Maybe you could check if the block has blockstate `lit: false`, and if so disable lighting a torch with it, at least until there is a proper solution. This would work for all of the vanilla blocks and wouldn't cause additional problems with modded ones.

**Comment by WolfieWaffle** [comment]
hm, I think I can do that yea
